source 'https://rubygems.org'

# group :production, :staging do
#   gem 'rack-cache', :require => 'rack/cache'
# end

gem 'rails', '~> 6.0'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'foreman'
# gem 'exception_notification'

# SEO
gem 'sitemap_generator'

# Cron
# gem 'whenever', require: false

# Server
gem 'puma'

#Database
gem 'pg'
gem 'redis'

# Templating
gem 'slim'
gem 'slim-rails', group: :development

# Form helpers
gem 'simple_form', '>= 4.0'

# Pagination
# gem 'kaminari'

# Date and time
gem 'chronic'

# Queues
gem 'sidekiq'
# gem 'queue_classic'

# Javascript
gem 'turbolinks', '~> 5'
gem 'webpacker'

# JSON
# gem 'jbuilder'

# CSS
gem 'sass-rails', '>= 6'
gem 'uglifier', '>= 1.3.0'
gem 'autoprefixer-rails'

# Security
gem 'rack-attack'

# Emails
gem 'premailer-rails'

# Others
gem 'nokogiri'

group :development do
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails-erd' #generates ERD model diagrams
  gem 'annotate'
  # gem 'meta_request' (might break file upload)
  # gem 'xray-rails'   (might break js)
end

group :development, :test do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-byebug'
  gem 'faker'
  gem 'minitest-rails'
  gem 'guard-minitest'
  # gem 'spinach-rails'
  # gem 'guard-spinach'
end

group :test do
  gem 'timecop'
  gem 'capybara', '>= 2.15'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  #gem 'capybara-webkit' #brew install qt
  gem 'minitest-metadata', require: false
  gem 'minitest-rails-capybara'
  gem 'database_cleaner'
  gem 'minitest-reporters', require: false
  gem 'mocha'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end
