source 'https://rubygems.org'

# group :production, :staging do
#   gem 'rack-cache', :require => 'rack/cache'
# end

gem 'rails', '~> 5.1'
gem 'foreman'
gem 'dalli'
# gem 'exception_notification'

# SEO
gem 'sitemap_generator'

# Cron
# gem 'whenever', require: false

# Server
gem 'puma', '~> 3.0'
gem 'redis', '~> 3.0'

#Database
gem 'pg'
# gem 'activerecord-postgres-hstore'

# Templating
gem 'slim'
gem 'slim-rails', group: :development

# Form helpers
gem 'simple_form', '~> 3.0'

# Pagination
# gem 'kaminari'

# Date and time
gem 'chronic'

# Queues
gem 'sidekiq'
# gem 'queue_classic'

# Javascript
gem 'turbolinks', '~> 5'
gem 'jquery-turbolinks'
gem 'jquery-rails'

# JSON
# gem 'jbuilder'

# CSS
gem 'sass-rails','>= 5.0.0'
gem 'coffee-rails','>= 4.2.0'
gem 'uglifier', '>= 1.3.0'
gem 'autoprefixer-rails'

# Security
gem 'rack-attack'

group :development do
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails-erd' #generates ERD model diagrams
  gem 'annotate'
  # gem 'meta_request' (might break file upload)
  # gem 'xray-rails'   (might break js)
end

group :development, :test do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-byebug'
  gem 'faker'
  gem 'minitest-rails'
  gem 'guard-minitest'
  # gem 'spinach-rails'
  # gem 'guard-spinach'
end

group :test do
  gem 'timecop'
  gem 'capybara-screenshot'
  #gem 'capybara-webkit' #brew install qt
  gem 'minitest-metadata', require: false
  gem 'minitest-rails-capybara'
  gem 'database_cleaner'
  gem 'minitest-reporters', require: false
  gem 'mocha'
end

# group :doc do
#   # bundle exec rake doc:rails generates the API under doc/api.
#   gem 'sdoc', require: false
# end
